exports.zeroRow=  {
    cons_level_0: 0,
    cons_level_1: 0,
    cons_level_2: 0,
    cons_level_3: 0,
    amount_0: 0,
    amount_1: 0,
    amount_2: 0,
    amount_3: 0,
    tax_0: 0,
    tax_1: 0,
    tax_2: 0,
    tax_3: 0,
    totalToPay: 0,
    totalAmounts: 0,
    totalTaxes: 0,
    inscriptionTax: 0,
}